name: recipe_app
description: A recipe app built with bkend platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  provider: ^6.1.1
  go_router: ^14.0.0
  flutter_secure_storage: ^9.2.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.1.0
  intl: any
  image_picker: ^1.0.7
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
